# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
python:
  - "2.7"
# List the versions of Django you'd like to test against
env:
  - DJANGO_VERSION=1.5.11 REST_FRAMEWORK_VERSION=2.3.14
  - DJANGO_VERSION=1.6.8 REST_FRAMEWORK_VERSION=2.3.14
  - DJANGO_VERSION=1.6.8 REST_FRAMEWORK_VERSION=3.0.2
  - DJANGO_VERSION=1.7.1 REST_FRAMEWORK_VERSION=2.3.14
  - DJANGO_VERSION=1.7.1 REST_FRAMEWORK_VERSION=3.0.2
before_install:
  - export DJANGO_SETTINGS_MODULE=tests.test_settings
  - export PIP_USE_MIRRORS=true
# Tell it the things it will need to install when it boots
install:
   # Install the dependencies the app itself has
   # which in this case I choose to keep in a requirements file
 - pip install -r requirements.txt
   # Install whatever version of Django that's listed above
   # Travis is currently working on
 - pip install -q Django==$DJANGO_VERSION
 - pip install djangorestframework==$REST_FRAMEWORK_VERSION
 - pip install coveralls
# Tell Travis how to run the test script itself
script: coverage run --source=versatileimagefield runtests.py
after_success: coveralls
