# Send this build to the travis.ci container-based infrastructure
# which typically has more capacity than the open-source Linux pool
sudo: false
# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
matrix:
  include:
    - python: "2.7"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.4.7
    - python: "2.7"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.5.3
    - python: "2.7"
      env: DJANGO_VERSION=1.9.13 REST_FRAMEWORK_VERSION=3.5.3
    - python: "2.7"
      env: DJANGO_VERSION=1.10.7 REST_FRAMEWORK_VERSION=3.5.3
    - python: "2.7"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.6.2
    - python: "3.4"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.4.7
    - python: "3.4"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.4"
      env: DJANGO_VERSION=1.9.13 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.4"
      env: DJANGO_VERSION=1.10.7 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.4"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.6.2
    - python: "3.4"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.4"
      env: DJANGO_VERSION=2.0.1 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.5"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.4.7
    - python: "3.5"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.5"
      env: DJANGO_VERSION=1.9.13 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.5"
      env: DJANGO_VERSION=1.10.7 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.5"
      env: DJANGO_VERSION=1.11.2 REST_FRAMEWORK_VERSION=3.6.2
    - python: "3.5"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.5"
      env: DJANGO_VERSION=2.0.1 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.6"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.4.7
    - python: "3.6"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.6"
      env: DJANGO_VERSION=1.9.13 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.6"
      env: DJANGO_VERSION=1.10.7 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.6"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.6.2
    - python: "3.6"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.6"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.8.2
    - python: "3.6"
      env: DJANGO_VERSION=2.0.1 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.6"
      env: DJANGO_VERSION=2.0.1 REST_FRAMEWORK_VERSION=3.8.2
    - python: "3.6"
      env: DJANGO_VERSION=2.1.1 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.6"
      env: DJANGO_VERSION=2.1.1 REST_FRAMEWORK_VERSION=3.8.2
    - python: "3.7"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=2.0.1 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.7"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=2.0.1 REST_FRAMEWORK_VERSION=3.8.2
    - python: "3.7"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=2.1.1 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.7"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=2.1.1 REST_FRAMEWORK_VERSION=3.8.2
before_install:
  - export DJANGO_SETTINGS_MODULE=tests.test_settings
# Tell it the things it will need to install when it boots
install:
   # Install the dependencies the app itself has
   # which in this case I choose to keep in a requirements file
 - pip install -e .
   # Install whatever version of Django that's listed above
   # Travis is currently working on
 - pip install -q Django==$DJANGO_VERSION
 - pip install djangorestframework==$REST_FRAMEWORK_VERSION
 - pip install coveralls
 - pip install flake8
# Tell Travis how to run the test script itself
script:
- flake8 versatileimagefield/
- coverage run --parallel-mode --source=versatileimagefield runtests.py
- coverage run --parallel-mode --source=versatileimagefield post_processor_runtests.py
- coverage combine
after_success: coveralls
